[workspace]
channels = ["https://prefix.dev/conda-forge", "conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

# -------------------------------
# === Packaging Configuration ===
# -------------------------------
[package]
name = "raysect"
version = "0.9.2"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.config]
noarch = false
compilers = ["c"]
env = { SETUPTOOLS_SCM_PRETEND_VERSION = "0.9.2" }
extra-args = ["--config-settings=editable-verbose=true"]

[workspace.build-variants]
python = ["3.10.*", "3.11.*", "3.12.*", "3.13.*"]

[package.build-dependencies]
c-compiler = "*"
meson = "*"
ninja = "*"

[package.host-dependencies]
uv = "*"
pkg-config = "*"
python = "*"
meson-python = "*"
setuptools-scm = "*"
cython = ">=3.1,<4"
numpy = ">=2"

[package.run-dependencies]
matplotlib-base = ">=3.10.0,<4"
opencv = "*"

# ---------------------------------
# === Development Configuration ===
# ---------------------------------
[dev]
raysect = { path = "." }

[dependencies]
ipython = "*"

[tasks]
prebuild = { cmd = [
  "python",
  "dev/generate_meson_files.py",
], description = "🔄 Generate meson.build files" }
build = { env = { BUILD_PATH = "$PIXI_PROJECT_ROOT/build/$(python $PIXI_PROJECT_ROOT/dev/build/abi.py)" }, cmd = [
  "meson",
  "setup",
  "$BUILD_PATH",
  "&&",
  "meson",
  "compile",
  "-C",
  "$BUILD_PATH",
], description = "🔧 Build cython extensions", depends-on = [
  "prebuild",
] }

# Documentation tasks without Raysect installation
doc-clean = { cmd = [
  "rm",
  "-rf",
  "build",
], cwd = "docs", description = "🔥 Clean the docs build directory" }
doc-serve = { cmd = [
  "python",
  "-m",
  "http.server",
  "8000",
  "--directory",
  "build/html",
], cwd = "docs", description = "🚀 Start a local server for the docs" }

# === Testing feature ===
[feature.tests.dependencies]
raysect = { path = "." }

[feature.tests.tasks]
test = { cmd = [
  "python",
  "-m",
  "unittest",
  "-v",
], description = "🧪 Run the tests" }

# === Documentation feature ===
[feature.docs.dependencies]
sphinx = "*"
sphinx_rtd_theme = "*"

[feature.docs.pypi-dependencies]
raysect = { path = "." }

[feature.docs.tasks]
doc-build = { cmd = [
  "sphinx-build",
  "-b",
  "{{ target }}",
  "source",
  "build/{{ target }}",
], cwd = "docs", args = [
  { arg = "target", default = "html" },
], description = "📝 Build the docs" }

# === Linting feature ===
[feature.lint.dependencies]
ruff = "*"
cython-lint = "*"

# === Python environment features ===
[feature.py310.dependencies]
python = "3.10.*"
[feature.py313.dependencies]
python = "3.13.*"

[environments]
default = { features = ["py313"], solve-group = "py313" }
docs = { features = ["py313", "docs"], solve-group = "py313" }
tests = { features = ["py313", "tests"], solve-group = "py313" }
tests-py313 = { features = [
  "py313",
  "tests",
], solve-group = "py313" } # alias of tests
tests-py310 = ["py310", "tests"]
lint = { features = ["lint"], no-default-feature = true }
